Repository PIVX-Project/PIVX-SPMT, pull requests merged in 2019-11, with the labels that each got.

#17 [Travis] Fix windows build
  .travis.yml
Labels: bug, build

#18 [Bug] Fix updateRPCstatus to properly signal disconnection
  src/mainWindow.py
Labels: bug

#20 Change windows icon to multi-resolution format
  img/spmt.ico
Labels: GUI, build

#19 [Build] Add a basic windows NSIS installer script
  setup.nsi
Labels: build

#14 [Core] Introduce new message signatures for MNB and MNP
  src/constants.py
  src/masternode.py
  src/utils.py
Labels: PIVX core

#16 Sign text messages with HW devices
  README.md
  docs/img/tools_01.png
  docs/img/tools_02.png
  docs/img/tools_03.png
  docs/img/tools_04.png
  docs/img/tools_05.png
  docs/img/tools_06.png
  docs/img/tools_07.png
  docs/img/tools_08.png
  docs/tools.md
  src/ledgerClient.py
  src/mainWindow.py
  src/masternode.py
  src/pivx_hashlib.py
  src/qt/dlg_signmessage.py
  src/spmtApp.py
  src/trezorClient.py
  src/utils.py
  src/version.txt
Labels: feature

#21 [Build] Onefile binaries
  .travis.yml
  SecurePivxMasternodeTool.spec
  setup.nsi
Labels: build

#22 [Bug] Fix segfault with stdout redirection on windows
  src/constants.py
  src/mainWindow.py
  src/misc.py
  src/qt/dlg_selectMNs.py
Labels: bug
