Repository PIVX-Project/PIVX-SPMT, pull requests merged in 2024-04, with the labels that each got.

#54 [GA] Update actions to node20
  .github/workflows/main.yaml
Labels: Build

#52 [GUI] TorV3 Support
  src/utils.py
Labels: enhancement

#55 [GUI] Update total available budget
  src/qt/dlg_budgetProjection.py
Labels: GUI

#56 [Build] Update windows deployment
  LICENSE.txt
  img/nsis-header.bmp
  img/nsis-wizard.bmp
  img/spmt.ico
  setup.nsi
Labels: Build

#57 [Build] Updatate gitignore rules
  .gitignore
Labels: Build

#58 [Core] Update explorer endpoints
  src/blockbookClient.py
Labels: Bug

#59 [Doc] Update Readme header badges
  README.md
Labels: Documentation

#62 [GUI] Fix transparency for status/logo images
  img/icon_grayLedH.png
  img/icon_greenLedH.png
  img/icon_halfPurpleLedH.png
  img/icon_purpleLedH.png
  img/spmtLogo_horiz.png
Labels: GUI
